version: 2.1
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty # primary container will run Ubuntu Trusty
    steps:
      - run: 
          name: name
          command: name
          working_directory: ~/project
            
