version: 2.1
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty # primary container will run Ubuntu Trusty
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            cd $(CIRCLE_WORKING_DIRECTORY)
            make
